# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0.xci
# IP: The module: 'system_PSR_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PSR_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PSR_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PSR_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0.xci
# IP: The module: 'system_PSR_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PSR_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PSR_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Bakuboys101/Desktop/Jr_Year_Spring/ECE_1195/Lab_5/vivado/lab5/lab5.srcs/sources_1/bd/system/ip/system_PSR_0/system_PSR_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PSR_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
